[package]
name = "zlgcan_common"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { version = "1.0.58" }
serde_yaml = "0.9.33"
serde = { version = "1.0.197", features = ["derive"] }
