[package]
name = "zlgcan-driver-rs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
zlgcan_common = { version = "0.3.3" }
zlgcan_driver = { version = "0.3.3" }
