[package]
name = "zlgcan-driver-rs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zlgcan_common = { version = "0.3.2", path = "../zlgcan-common" }
zlgcan_driver = { version = "0.3.2", path = "../zlgcan-driver" }
