[package]
name = "zlgcan_driver"
version = "0.2.0"
edition = "2021"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
license-file = "LICENCE-GPL-V3"
description = "A ZLGCAN driver with rust."
homepage = "https://github.com/zhuyu4839/zlgcan-driver-rs"
repository = "https://github.com/zhuyu4839/zlgcan-driver-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rand = "0.8.5"

[dependencies]
zlgcan_common = { version = "0.2.0" }
dlopen2 = "0.7.0"
log = "0.4.21"
log4rs = "1.3.0"
lazy_static = "1.4.0"

[lib]
crate-type = ["cdylib"]
bench = false
doc = true
