[package]
name = "zlgcan_driver"
version = "2.0.0-rc1"
edition = "2021"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
license-file = "../LICENCE-GPL-V3"
description = "A ZLGCAN driver with rust."
homepage = "https://github.com/zhuyu4839/zlgcan-driver-rs"
repository = "https://github.com/zhuyu4839/zlgcan-driver-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rand = "0.8.5"

[dependencies]
log = { workspace = true }
lazy_static = { workspace = true }
dlopen2 = { workspace = true }
zlgcan_common = { workspace = true }

#[lib]
#crate-type = ["cdylib"]
#bench = false
#doc = true
